### ISSUE TITLE
usage of this package

### ISSUE THREAD

**Issue by tiralonghipol** [KumarRobotics/camera_base#3]
Hi.
I would like to write a ros driver for this camera:
http://www.uctronics.com/arducam-cmos-ar0134-1-3-inch-1-2mp-color-camera-module.html
which is used togheter with its shield:
http://www.uctronics.com/arducam-usb-camera-shield.html

Do you think I could use this package in order to create a ros wrapper/driver?
Any hint?
Thank you!

**Comment by kartikmohta** [comment]
Note that this is just a high level helper package, it sits above any hardware specific API layer. You're free to use it, some examples of drivers using this helper can be found at https://github.com/KumarRobotics/flea3/ and https://github.com/KumarRobotics/bluefox2/.
